version: '3.8'

services:
  childapi:
    build:
      context: .
      dockerfile: ChildAPI/Dockerfile
    ports:
      - "5000:80"
    environment:
      - LLM_ENDPOINT=
      - LLM_API_KEY=

  childapp:
    build:
      context: .
      dockerfile: ChildApp/Dockerfile
    depends_on:
      - childapi
    environment:
      - LLM_ENDPOINT=
      - LLM_API_KEY=
